apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Mventory
  description: The inventory backend for Makerspaces
  annotations:
    github.com/project-slug: 'makemonmouth/mventory'
    grafana/tag-selector: "mventory"
    prometheus.io/alert: rate(django_http_requests_latency_including_middlewares_seconds_bucket{_app="mventory",le="0.5"}[5m])
    prometheus.io/rule: rate(django_http_requests_latency_including_middlewares_seconds_bucket{_app="mventory",le="0.5"}[5m])
spec:
  type: website
  owner: matt@doics.co
  lifecycle: production
  dependsOn: 
    - Resource:default/MVentory-Database
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: MVentory-Database
  description: The database backend for MVentry
  annotations:
    github.com/project-slug: 'makemonmouth/mventory'
    grafana/tag-selector: "mventory"
    prometheus.io/alert: HighRequestLatency
    prometheus.io/rule: HighRequestLatency
spec:
  type: database
  owner: matt@doics.co
  lifecycle: production
