apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Mventory
  description: The inventory backend for Makerspaces
  annotations:
    backstage.io/techdocs-ref: dir:docs/
    github.com/project-slug: 'makemonmouth/mventory'
    grafana/tag-selector: "mventory"
    sentry.io/project-slug: "mventory"
    prometheus.io/alert: MventoryHighErrorRate
spec:
  type: service
  owner: matt@doics.co
  lifecycle: production
  providesApis:
    - mventory-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mventory-api
  description: The MVentory API
spec:
  type: internal
  lifecycle: production
  owner: matt@doics.co
  definition: "The MVentory API"
