apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Mventory
  description: The inventory backend for Makerspaces
  annotations:
    github.com/project-slug: 'makemonmouth/mventory'
    grafana/tag-selector: "mventory"
spec:
  type: website
  owner: matt@doics.co
  lifecycle: production
