# Generated by Django 3.2.4 on 2021-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
                ('unit_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
