# Generated by Django 3.2.4 on 2021-06-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, max_length=5, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, max_length=5, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room')),
            ],
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_row', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_column', models.CharField(blank=True, max_length=5, null=True)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storageunit')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=100)),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.componentmeasurementunit')),
                ('storage_bin', models.ManyToManyField(to='inventory.StorageBin')),
            ],
        ),
    ]
