# Generated by Django 3.2.4 on 2021-06-15 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_building_component_room_storagebin_storageunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
