# Generated by Django 3.2.4 on 2021-06-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_component_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='product_code',
            new_name='sku',
        ),
    ]
