# Generated by Django 3.2.4 on 2021-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_product_code_component_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mpn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='upc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
