# Generated by Django 3.2.5 on 2022-01-08 19:34

from django.db import migrations

def CreateInitialMembershipLevel(apps, schema_editor):
    MembershipLevel = apps.get_model("inventory", "MembershipLevel")
    new_ml = MembershipLevel()
    new_ml.name = "Core"
    new_ml.monthly_fee = 10
    new_ml.save()



class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_membermembershiplevel_membershiplevel_profile'),
    ]

    operations = [
    ]
