# Generated by Django 3.2.5 on 2022-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20220305_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsupplier',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='GBP', max_length=3),
        ),
    ]
