# Generated by Django 3.2.5 on 2022-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_componentsupplier_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentsupplier',
            old_name='cost',
            new_name='bought_at',
        ),
        migrations.RenameField(
            model_name='componentsupplier',
            old_name='price',
            new_name='members_price',
        ),
        migrations.AddField(
            model_name='componentsupplier',
            name='buying_discount_from_rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='componentsupplier',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
